### ISSUE TITLE
Pagination doesn't work

### ISSUE THREAD

**Issue by jrenggli** [neos/Neos.MarketPlace#14]
Switching to other pages displays the same results. I'm always getting the first 25 entries.
- https://www.neos.io/download-and-extend/packages.html
- https://www.neos.io/download-and-extend/packages.html?--typo3-typo3cr-search-viewhelpers-widget-paginateviewhelper%5B%40package%5D=&--typo3-typo3cr-search-viewhelpers-widget-paginateviewhelper%5B%40subpackage%5D=&--typo3-typo3cr-search-viewhelpers-widget-paginateviewhelper%5B%40controller%5D=&--typo3-typo3cr-search-viewhelpers-widget-paginateviewhelper%5B%40action%5D=index&--typo3-typo3cr-search-viewhelpers-widget-paginateviewhelper%5BcurrentPage%5D=5

**Comment by dfeyer** [comment]
This as been solved, now we try to tackle some performance issue, check #15
